language: node_js

node_js: ['6']

install:
- yarn install

script:
- yarn test

before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

deploy:
  provider: npm
  skip_cleanup: true
  script: npm publish .
  on:
    tags: true
